name: '[Enter] & [Esc]'
favicon: null
layout_spectrum: 0.49723
typography_spectrum: 0.09289
title: '[Enter] & [Esc]'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
